version: 0.2

env:
  variables:
    BACKEND: $ECR_URI/backend
    FRONTEND: $ECR_URI/frontend
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      docker: 24
    commands:
      - echo Install phase:\ ensure aws cli available
      - if ! command -v aws &> /dev/null; then echo "'aws cli' not found. Please install it"; exit 1; fi
      - aws --version
      - echo "Docker version:" && docker --version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo "Building images..."
      - docker compose build

  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - docker compose -f docker-compose.yml push
      - echo "Images pushed successfully."