version: 0.2

env:
  variables:
    BACKEND: $ECR_URI/backend
    FRONTEND: $ECR_URI/frontend
    IMAGE_TAG: latest

phases:
  install:
    commands:
      - echo Install phase, ensure aws cli available
      - command -v aws || (echo "'AWS cli' not found. Please install it"; exit 1)
      - echo aws --version
      - echo docker --version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo "Building images..."
      - docker compose -f infra/docker-compose.yml build

  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - docker compose -f infra/docker-compose.yml push
      - echo "Images pushed successfully."